# ============================================================
# morsewurst/server/user_registry.py
# ============================================================

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path
from typing import Any

from morsewurst.network.protocol import sanitize_installation_id


def installation_id_hash(installation_id: object) -> str:
    clean = sanitize_installation_id(installation_id)
    if not clean:
        return ""

    digest = hashlib.sha256(
        f"morsewurst-installation-v1|{clean}".encode("utf-8")
    ).hexdigest()

    return f"sha256:{digest}"


class UserRegistry:
    """Small privacy-preserving persistent registry for seen installations.

    This stores only a hash of the random installation id generated by the
    client. It does not store IP addresses, hardware identifiers, Morse content
    or raw telemetry.
    """

    def __init__(self, storage_path: str | Path, *, enabled: bool = True) -> None:
        self.storage_path = Path(storage_path)
        self.enabled = bool(enabled)
        self.users: dict[str, dict[str, Any]] = {}
        self._loaded = False

        if self.enabled:
            self.load()

    def load(self) -> None:
        self._loaded = True

        try:
            data = json.loads(self.storage_path.read_text(encoding="utf-8"))
        except Exception:
            self.users = {}
            return

        if not isinstance(data, dict):
            self.users = {}
            return

        users = data.get("users")
        if not isinstance(users, dict):
            self.users = {}
            return

        clean: dict[str, dict[str, Any]] = {}

        for key, value in users.items():
            if not isinstance(key, str) or not key.startswith("sha256:"):
                continue
            if not isinstance(value, dict):
                continue
            clean[key] = value

        self.users = clean

    def save(self) -> None:
        if not self.enabled:
            return

        self.storage_path.parent.mkdir(parents=True, exist_ok=True)

        payload = {
            "version": 1,
            "saved_at": time.time(),
            "users": self.users,
        }

        tmp = self.storage_path.with_suffix(self.storage_path.suffix + ".tmp")
        tmp.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True),
            encoding="utf-8",
        )
        tmp.replace(self.storage_path)

    def record_connect(self, session: Any) -> None:
        if not self.enabled:
            return

        key = str(getattr(session, "installation_id_hash", "") or "")
        if not key.startswith("sha256:"):
            return

        now = time.time()
        callsign = str(getattr(session, "callsign", "") or "")[:40]
        room_key = str(getattr(session, "room_key", "") or "")[:80]
        room_id = str(getattr(session, "room_id", "") or "")[:20]
        client_version = str(getattr(session, "client_version", "") or "")[:40]
        protocol_version = int(getattr(session, "protocol_version", 0) or 0)

        user = self.users.get(key)
        if user is None:
            user = {
                "installation_id_hash": key,
                "first_seen_at": now,
                "connect_count": 0,
                "callsigns_seen": [],
            }

        user["last_seen_at"] = now
        user["last_connect_at"] = now
        user["last_callsign"] = callsign
        user["last_room_key"] = room_key
        user["last_room_id"] = room_id
        user["last_client_version"] = client_version
        user["last_protocol_version"] = protocol_version
        user["connect_count"] = int(user.get("connect_count") or 0) + 1

        callsigns_seen = user.get("callsigns_seen")
        if not isinstance(callsigns_seen, list):
            callsigns_seen = []

        if callsign and callsign not in callsigns_seen:
            callsigns_seen.append(callsign)

        user["callsigns_seen"] = callsigns_seen[-10:]

        self.users[key] = user
        self.save()

    def record_disconnect(self, session: Any) -> None:
        if not self.enabled:
            return

        key = str(getattr(session, "installation_id_hash", "") or "")
        if not key.startswith("sha256:"):
            return

        user = self.users.get(key)
        if user is None:
            return

        now = time.time()
        user["last_seen_at"] = now
        user["last_disconnect_at"] = now
        user["last_room_key"] = str(getattr(session, "room_key", "") or "")[:80]
        user["last_room_id"] = str(getattr(session, "room_id", "") or "")[:20]
        user["last_callsign"] = str(getattr(session, "callsign", "") or "")[:40]

        self.users[key] = user
        self.save()

    def stats(self) -> dict[str, int]:
        now = time.time()
        day_seconds = 24 * 60 * 60
        week_seconds = 7 * day_seconds

        known = 0
        seen_24h = 0
        seen_7d = 0

        for user in self.users.values():
            if not isinstance(user, dict):
                continue

            known += 1

            try:
                last_seen = float(user.get("last_seen_at") or 0)
            except Exception:
                last_seen = 0

            age = now - last_seen

            if 0 <= age <= day_seconds:
                seen_24h += 1
            if 0 <= age <= week_seconds:
                seen_7d += 1

        return {
            "known_installations": known,
            "seen_24h": seen_24h,
            "seen_7d": seen_7d,
        }