# ============================================================
# morsewurst/core/wxmor/locations.py
# ============================================================

from __future__ import annotations

# Easy-to-extend location list used by the random WX-MOR generator.
#
# - WXMOR_LOCAL_LOCATIONS are not official airport identifiers.
#   They are local/agreed training locations that you may freely rename.

WXMOR_ICAO_LOCATIONS: list[str] = [
    "EFHK", "ESGG", "ENBR", "EKYT", "BIAR", "EETN", "EVRA", "EYKA",
    "EGPD", "EIKN", "EDDB", "LFKB", "EHAM", "EBCI", "LEAL", "LPFR",
    "LIBD", "LSGG", "LOWG", "EPKK", "KALB", "CYYC", "MMAA", "SBCF",
    "SABE", "SCFA", "YPAD", "NZAA", "RJSA", "ZBOW", "VAAH", "OMAA",
    "OAHR", "TAPA", "LATI", "UDSG", "FNLU", "NSTU", "TNCA", "UBBB",
    "LQTZ", "TBPB", "VGEG", "DFOO", "LBBG", "OBBI", "HBBA", "DBBB",
    "TXKF", "WBSB", "SLCB", "TNCB", "MYGF", "VQPR", "FBPM", "UMBB",
    "MZBZ", "YPCC", "FZNA", "FEFF", "FCBB", "DIAP", "NCRG", "FKKD",
    "SKBQ", "MRLB", "MUCM", "GVAC", "TNCC", "LCLK", "LKKV", "HDAM",
    "MDLR", "DAAG", "SEGU", "HESX", "GMMH", "HAAB", "NFFN", "EGYP",
    "PTSA", "EKVG", "FOON", "TGPY", "UGSB", "SOCA", "DGAA", "LXGB",
    "BGGH", "GBYD", "GUCY", "TFFR", "FGBT", "LGIR", "MGGT", "PGUM",
    "GGOV", "SYCJ", "VHHH", "MHRO", "LDDU", "MTCH", "LHBP", "WAPP",
    "LLER", "EGNS", "ORER", "OIAA", "MKJP", "OJAM", "HKEL", "UCFM",
    "VDTI", "PLCH", "FMCH", "TKPK", "ZKPY", "RKPK", "OKKK", "MWCR",
    "UATE", "VLLB", "OLBA", "TLPL", "VCBI", "GLRB", "FXMM", "ELLX",
    "HLLQ", "GMAD", "LUKK", "LYPG", "FMMI", "PKMJ", "LWSK", "GABS",
    "VYMD", "ZMCK", "VMMC", "PGRO", "TFFF", "GQPP", "TRPG", "LMML",
    "FIMP", "VRMG", "FWCL", "WMKI", "FQBR", "FYWB", "NWWW", "DRRN",
    "DNAA", "MNMG", "VNKT", "OOMS", "MPTO", "SPQU", "NTAA", "AYNZ",
    "RPVB", "OPIS", "TJSJ", "PTRO", "SGAS", "OTBD", "FMEP", "LRBC",
    "LYBE", "UNAA", "HRYR", "OEAB", "AGGH", "FSIA", "HSSK", "WSSS",
    "LJLJ", "LZIB", "GFLL", "GOBD", "HCMF", "SMJP", "HJJJ", "FPST",
    "MSLP", "TNCM", "OSAP", "FDSK", "MBPV", "FTTJ", "DXXX", "VTBD",
    "UTDT", "WPDL", "UTAA", "DTTJ", "NFTF", "LTAC", "TTPP", "RCYU",
    "HTKJ", "UKLL", "HUEN", "SUMU", "UZFA", "TVSA", "SVBC", "TUPJ",
    "TIST", "VVCT", "NVVV", "NLWW", "NSFA", "BKPR", "OYAA", "FMCZ",
    "FABL", "FLHN", "FVJN", "EFIV", "ESNQ", "ENBO", "EKAH", "BIKF",
    "EVLA", "EYPA", "EGAA", "EICK", "EDDW", "LFOB", "EHEH", "EBOS",
    "LEBL", "LPMA", "LIPE", "LSZH", "LOWI", "EPGD", "KABQ", "CYEG",
    "MMAS", "SBBE", "SAEZ", "SCIE", "YBBN", "NZCH", "RJFF", "ZBAA",
    "VIAR", "OMAL", "OAKB", "UDYZ", "FNBJ", "UBBG", "LQBK", "VGHS",
    "DFFD", "LBPD", "SLLP", "MYNN", "FBSK", "UMMS", "FZAA", "FCPP",
    "DIYO", "FKKR", "SKBO", "MROC", "MUHA", "GVNP", "LCPH", "LKMT",
    "MDPC", "DABB", "SEQM", "HEAX", "GMML", "HADR", "NFNA", "PTKK",
    "FOOL", "UGKO", "DGSI", "FGSL", "LGKV", "MHPR", "LDPL", "MTPP",
    "LHDC", "WALL", "LLBG", "ORBI", "OIAW", "MKJS", "OJAI", "HKKI",
    "UCFO", "VDSV", "NGTA", "RKTU", "UATT", "VLPS", "VCCC", "HLLB",
    "GMFO", "FMNM", "LWOH", "GATB", "VYNT", "ZMUB", "GQNO", "VRMH",
    "FWKI", "WMKJ", "FQMA", "FYWH", "DNAS", "VNBW", "OOSA", "SPHI",
    "AYPY", "RPVI", "OPFA", "SGES", "OTHH", "FMEE", "LRBV", "LYNI",
    "UHWW", "OEDF", "HSPN", "GOOY", "HCMH", "OSDI", "DXNG", "VTBS",
    "UTDD", "WPOC", "UTAN", "DTTX", "NFTV", "LTAI", "TTCP", "RCQC",
    "HTDA", "UKFF", "UZSB", "SVBM", "VVDN", "OYMK", "FACT", "FLKK",
    "FVFA", "EFKT", "ESSL", "ENEV", "EKBI", "EYVI", "EGBB", "EIDW",
    "EDLP", "LFBD", "EHGG", "EBBR", "LEBB", "LPPT", "LIBR", "LOWK",
    "EPRZ", "PANC", "CYHZ", "MMUN", "SBBV", "SAVC", "SCDA", "YBRM",
    "NZQN", "RJCH", "ZBAD", "VOBL", "OMDB", "OAKN", "UBBN", "LQMO",
    "VGSY", "LBSF", "SLOR", "MYSM", "FBKE", "FZIC", "FKYS", "SKCL",
    "MUHG", "GVBA", "LCEN", "LKPD", "MDST", "DABT", "SESA", "HESN",
    "HALA", "PTYA", "FOOG", "UGTB", "DGLE", "FGMY", "LGKR", "MHLM",
    "LDRI", "LHPP", "WITT", "ORMM", "OIKB", "OJAQ", "HKMO", "UCFL",
    "VDSA", "RKTN", "UAAA", "VLVT", "VCCJ", "HLLM", "GMMW", "FMNN",
    "VYYY", "VRMM", "WBKK", "FQNP", "DNBC", "OOSH", "SPZO", "RPVM",
    "OPGW", "SGEN", "LRBS", "URWA", "OESK", "HCMM", "VTCC", "UTDL",
    "UTAT", "DTTA", "LTFE", "RCKH", "HTMW", "UKLU", "UZFN", "SVPR",
    "VVCI", "OYRN", "FALE", "FLMF", "EFKU", "ESPA", "ENCN", "EKCH",
    "EGGD", "EINN", "EDVK", "LFRB", "EHBK", "LEMI", "LPPD", "LIEE",
    "LOWL", "EPKT", "KATL", "CYLW", "MMCU", "SBBR", "SACO", "SCIP",
    "YBCS", "NZWN", "RJOA", "ZYCC", "VABP", "OMDW", "OAMS", "LQSA",
    "LBWN", "SLUY", "FBMN", "FZQA", "SKCG", "MUVR", "GVSV", "LKPR",
    "MDSD", "DAUB", "SETN", "HEAT", "HAJJ", "LGKO", "LDSP", "WAOO",
    "ORKK", "OIMB", "HKJK", "VDPP", "RKNY", "UACC", "VCRI", "HLGD",
    "GMMN", "FMMT", "WBGG", "FQTT", "DNBK", "SPQT", "RPMD", "OPKC",
    "LRCL", "UNBB", "OEAO", "VTCT", "UTDK", "UTAV", "LTBS", "RCMQ",
    "HTZA", "UKOO", "UZNN", "SVMG", "VVNB", "OYSN", "FAEL", "FLSK",
    "EFLP", "ESMS", "ENGM", "EKOD", "EGFF", "EDLW", "LFSB", "EHRD",
    "GCFV", "LPPR", "LIPX", "LOWS", "EPLB", "KAUS", "CYUL", "MMCS",
    "SBKP", "SAME", "SCTE", "YPDN", "RJFK", "ZGHA", "VEBS", "OMFJ",
    "SLVR", "SKRG", "MUSC", "LKCS", "DAAE", "HECA", "LGRP", "LDZA",
    "WIDD", "ORNI", "OIFM", "RKPC", "UATG", "GMMX", "WMKL", "DNEN",
    "SPJL", "RPMR", "OPLA", "LRCK", "USCC", "OEHL", "VTSS", "LTFD",
    "RCNN", "UKDE", "UZSS", "SVMI", "VVTS", "OYSY", "FAGG", "EFMA",
    "ESKN", "ENTO", "EGPH", "EDDC", "LFLC", "LEGE", "LIMF", "LOWW",
    "EPMO", "KBWI", "CYOW", "MMCZ", "SBCY", "SAZN", "SCCI", "YMAV",
    "RJNK", "ZUTF", "VOCL", "OMRK", "SLAL", "SKSP", "MUCU", "DAOI",
    "HEAL", "LGSR", "LDZD", "WIMM", "ORBM", "OIIP", "RKJB", "UAOL",
    "GMMZ", "WMKP", "DNIL", "SPJC", "RPVK", "OPMT", "LRCV", "UIAA",
    "OERS", "VTSG", "LTBY", "RCSS", "UZTT", "SVMC", "VVCR", "FAPE",
    "EFOU", "ESSA", "ENZV", "EGPF", "EDDL", "LFLL", "GCLP", "LICC",
    "EPPO", "KBHM", "CYQB", "MMCL", "SBCT", "SARE", "SCEL", "YBCG",
    "RJFR", "ZUUU", "VICG", "OMSJ", "DABC", "HEAR", "LGSA", "WIHH",
    "OIKK", "RKSS", "UAKK", "GMMD", "WMKK", "DNKA", "SPCL", "RPMY",
    "OPPS", "LRIA", "URMG", "OEAH", "VTSM", "LTAJ", "RCTP", "UZNU",
    "SVVA", "VVPQ", "FALA", "EFRO", "ESOW", "ENTC", "EGNM", "EDDE",
    "LFKF", "LEIB", "LIMC", "EPSC", "KBOI", "CYXE", "MMGL", "SBFL",
    "SAWG", "SCQP", "YMHB", "RJBE", "ZUCK", "VOMM", "OMAD", "DAAJ",
    "HEGN", "LGAV", "WIII", "OIBK", "RKSI", "UACK", "GMME", "WMSA",
    "DNKN", "SPRU", "RPLI", "OPQT", "LROD", "UIII", "OEJN", "VTSP",
    "LTBJ", "VVLT", "FAOR", "EFTP", "ESNU", "ENVA", "EGGP", "EDDF",
    "LFQQ", "LEMD", "LIRQ", "EPWA", "KBOS", "CYYT", "MMHO", "SBFZ",
    "SAAR", "YBSU", "RJFT", "ZYTL", "VOCB", "DAOO", "HELX", "LGTS",
    "WADD", "OIMM", "UAUU", "GMFF", "DNMM", "SPSO", "RPLK", "OPST",
    "LROP", "UMKK", "OEMA", "VTBU", "LTFM", "FAKM", "EFTU", "ESSV",
    "ENAL", "EGKK", "EDFH", "LFML", "LEMH", "LIMJ", "EPWR", "KBUF",
    "CYYZ", "MMBT", "SBFI", "SASA", "YMML", "RJNS", "ZBDT", "VEGT",
    "DAAV", "HEMA", "WAAA", "OIKQ", "UAOO", "GMTT", "DNMA", "RPLC",
    "OPSD", "LRSB", "UWKD", "OEPA", "VTUD", "LTAU", "FAKN", "EFVA",
    "EGLL", "EDNY", "LFMT", "LEMG", "LICA", "EPLL", "KBUR", "CYVR",
    "MMZH", "SBGO", "SAZS", "YPPH", "RJOM", "ZLDH", "VIHX", "DAAT",
    "HEMM", "WAMM", "OISS", "UASP", "GMTN", "DNPO", "RPLL", "OPTU",
    "LRSV", "UNEE", "OEGS", "LTAN", "FAPP", "EGSS", "EDDG", "LFMN",
    "LEPA", "LIRN", "KCHS", "CYYJ", "MMLT", "SBJP", "SANT", "YPPD",
    "RJFM", "ZHEC", "VIHR", "DAON", "HEPS", "WADL", "OITT", "UACP",
    "GMAZ", "DNSO", "RPLB", "LRTR", "URKK", "OERK", "LTAZ", "EGGW",
    "EDDH", "LFPB", "LEAS", "LIEO", "KCLT", "CYWG", "MMMZ", "SBMO",
    "SASJ", "YSWS", "RJFU", "ZSFZ", "VOHS", "HESH", "WIEE", "OIIE",
    "UASS", "RPVP", "UNKL", "OENN", "LTFJ", "EGCC", "EDDV", "LFPO",
    "LERS", "LIME", "KMDW", "MMSM", "SBEG", "YSSY", "ROAH", "ZGGG",
    "VEIM", "HESG", "WIOO", "OIII", "UAII", "RPMZ", "USCM", "OETB",
    "LTFO", "EGNT", "EDDK", "LFPG", "GCRR", "LICJ", "KORD", "MMMX",
    "SBNF", "YBWW", "RJOK", "ZGKL", "VAID", "HEBR", "WAHS", "OIZH",
    "UADD", "URML", "OETF", "LTAF", "EGNX", "EDJA", "LFST", "LEST",
    "LIRZ", "KCVG", "MMMY", "SBPA", "YWLM", "RJAA", "ZUGY", "VIJP",
    "WAJJ", "UAIT", "URMM", "OEYN", "LTDB", "EGPK", "EDDM", "LFBO",
    "LEZL", "LIBP", "KCLE", "MMMM", "SBPS", "RJSS", "ZLXN", "VASD",
    "WARR", "UARR", "UUDD", "OEDR", "LTCS", "EDDN", "GCXO", "LIRP",
    "KCOS", "MMMD", "SBPV", "RJSN", "ZJHK", "VOKN", "WAHQ", "UASK",
    "UUEE", "LTBA", "EDSB", "GCTS", "LIPR", "KCMH", "MMOX", "SBRF",
    "RJOB", "ZBLA", "VOCI", "WAHI", "UAKD", "UUWW", "EDDP", "LEVC",
    "LIRA", "KDAL", "MMPB", "SBRB", "RJAH", "ZSHC", "VECC", "UUBW",
    "EDDS", "LEZG", "LIRF", "KDFW", "MMPR", "SBGL", "RJBB", "ZYHB",
    "VILK", "ULMM", "EDLV", "LIPQ", "KDEN", "MMQT", "SBRJ", "RJOO",
    "ZSOF", "VOML", "USNN", "LIML", "KDSM", "MMSD", "SBSV", "RJFS",
    "ZBHH", "VOGA", "UWGG", "LIPH", "KDTW", "MMLO", "SBSL", "RJCC",
]

WXMOR_IATA_LOCATIONS: list[str] = [
    "HEL", "GOT", "BGO", "AAL", "AEY", "TLL", "RIX", "KUN",
    "ABZ", "NOC", "BER", "BIA", "AMS", "CRL", "ALC", "FAO",
    "BRI", "GVA", "GRZ", "KRK", "ALB", "YYC", "ACA", "CNF",
    "AEP", "ANF", "ADL", "AKL", "AOJ", "BAV", "AMD", "AUH",
    "HEA", "ANU", "TIA", "LWN", "LAD", "PPG", "AUA", "GYD",
    "TZL", "BGI", "CGP", "BOY", "BOJ", "BAH", "BJM", "COO",
    "BDA", "BWN", "CBB", "BON", "FPO", "PBH", "FRW", "BQT",
    "BZE", "CCK", "GOM", "BGF", "BZV", "ABJ", "RAR", "DLA",
    "BAQ", "LIR", "CMW", "SID", "CUR", "LCA", "KLV", "JIB",
    "LRM", "ALG", "GYE", "SPX", "VIL", "ADD", "NAN", "MPN",
    "KSA", "FAE", "MVB", "GND", "BUS", "CAY", "ACC", "GIB",
    "GOH", "BJL", "CKY", "PTP", "BSG", "HER", "GUA", "GUM",
    "OXB", "GEO", "HKG", "RTB", "DBV", "CAP", "BUD", "AMQ",
    "ETM", "IOM", "EBL", "ABD", "KIN", "ADJ", "EDL", "BSZ",
    "KTI", "CXI", "HAH", "SKB", "FNJ", "PUS", "KWI", "GCM",
    "SCO", "LPQ", "BEY", "UVF", "CMB", "ROB", "MSU", "LUX",
    "LAQ", "AGA", "RMO", "TGD", "TNR", "MAJ", "SKP", "BKO",
    "MDL", "UBN", "MFM", "ROP", "FDF", "NDB", "MNI", "MLA",
    "MRU", "GAN", "BLZ", "IPH", "BEW", "WVB", "NOU", "NIM",
    "ABV", "MGA", "KTM", "DQM", "PTY", "AQP", "PPT", "LAE",
    "BCD", "ISB", "SJU", "ROR", "ASU", "DIA", "ZSE", "BCM",
    "BEG", "ABA", "KGL", "AHB", "HIR", "SEZ", "KRT", "SIN",
    "LJU", "BTS", "FNA", "DSS", "BSA", "PBM", "JUB", "TMS",
    "SAL", "SXM", "ALP", "SHO", "PLS", "NDJ", "LFW", "DMK",
    "KQT", "DIL", "ASB", "DJE", "TBU", "ESB", "POS", "HUN",
    "JRO", "LWO", "EBB", "MVD", "AZN", "SVD", "BLA", "EIS",
    "STT", "VCA", "VLI", "WLS", "APW", "PRN", "ADE", "DZA",
    "BFN", "LVI", "BUQ", "IVL", "KRN", "BOO", "AAR", "KEF",
    "LPX", "PLQ", "BFS", "ORK", "BRE", "BVA", "EIN", "OST",
    "BCN", "FNC", "BLQ", "ZRH", "INN", "GDN", "ABQ", "YEG",
    "AGU", "BEL", "EZE", "CCP", "BNE", "CHC", "FUK", "PEK",
    "ATQ", "AAN", "KBL", "EVN", "NBJ", "GNJ", "BNX", "DAC",
    "OUA", "PDV", "LPB", "NAS", "GBE", "MSQ", "FIH", "PNR",
    "ASK", "GOU", "BOG", "SJO", "HAV", "RAI", "PFO", "OSR",
    "PUJ", "AAE", "UIO", "HBE", "EUN", "DIR", "SUV", "TKK",
    "LBV", "KUT", "KMS", "OCS", "KVA", "XPL", "PUY", "PAP",
    "DEB", "BPN", "TLV", "BGW", "AWZ", "MBJ", "AMM", "KIS",
    "OSS", "KOS", "TRW", "CJJ", "AKX", "PKZ", "RML", "BEN",
    "OUD", "MJN", "OHD", "TOM", "NYT", "ULN", "NKC", "HAQ",
    "LLW", "JHB", "MPM", "WDH", "ABB", "PHH", "MCT", "CIX",
    "POM", "ILO", "LYP", "AGT", "DOH", "RUN", "GHV", "INI",
    "VVO", "DMM", "PZU", "DKR", "HGA", "DAM", "LRL", "BKK",
    "DYU", "OEC", "BKN", "SFA", "VAV", "AYT", "TAB", "MZG",
    "DAR", "SIP", "BHK", "BRM", "DAD", "RIY", "CPT", "LUN",
    "HRE", "KTT", "LPI", "EVE", "BLL", "VNO", "BHX", "DUB",
    "PAD", "BOD", "GRQ", "BRU", "BIO", "LIS", "BDS", "KLU",
    "RZE", "ANC", "YHZ", "CUN", "BVB", "CRD", "IQQ", "BME",
    "ZQN", "HKD", "PKX", "BLR", "DXB", "KDH", "NAJ", "OMO",
    "ZYL", "SOF", "ORU", "ZSA", "BBK", "FKI", "NSI", "CLO",
    "HOG", "BVC", "ECN", "PED", "STI", "BLJ", "SNC", "ASW",
    "AWA", "YAP", "POG", "TBS", "TML", "SSG", "CFU", "SAP",
    "RJK", "PEV", "BTJ", "BSR", "BND", "AQJ", "MBA", "IKU",
    "SAI", "TAE", "ALA", "VTE", "JAF", "MJI", "NDR", "NOS",
    "RGN", "MLE", "BKI", "APL", "BCU", "BWA", "SLL", "CUZ",
    "CEB", "GWD", "ENO", "BBU", "ASF", "AJF", "MGQ", "CNX",
    "LBD", "TAZ", "TUN", "BJV", "KHH", "MWZ", "UDJ", "NMA",
    "PZO", "HPH", "SAH", "DUR", "MFU", "VFA", "KUO", "LLA",
    "KRS", "CPH", "BRS", "SNN", "KSF", "BES", "MST", "RMU",
    "PDL", "CAG", "LNZ", "KTW", "ATL", "YLW", "CUU", "BSB",
    "COR", "IPC", "CNS", "WLG", "HIJ", "CGQ", "BHO", "DWC",
    "MZR", "SJJ", "VAR", "UYU", "MUB", "FBM", "CTG", "VRA",
    "VXE", "PRG", "SDQ", "BSK", "ESM", "ATZ", "JIJ", "GEM",
    "KGS", "SPU", "BDJ", "KIK",
]

WXMOR_LOCAL_LOCATIONS: list[str] = [
    "KRUU", "MAUNU", "PATA", "OGELI", "PATOL", "TAIVA", "KESPU", "KAPYLA",
    "PAKILA", "PIRKK", "KALLIO", "PASILA", "KAMPPI", "KRUUN", "TOOLO", "HAAGA",
    "PITJA", "KONAL", "MALMI", "PUKIN", "VIIKKI", "HERTT", "MUNKK", "LAUTT",
    "ESPOO", "OTANI", "TAPIOL", "LEPPA", "MATIN", "KEILA", "NUUKS", "VANTA",
    "TIKKU", "KORSO", "MYRMA", "HAKUN", "SIPOO", "PORVOO", "LOHJA", "KERAV",
    "JARVE", "TUUSU", "HYVIN", "KARKK", "VIHTI", "KIRKK", "LAPPE", "IMATR",
    "KOUVO", "KOTKA", "HAMIN", "LAHTI", "HOLLO", "TAMPE", "NOKIA", "YPIRK",
    "VALKE", "HAMEE", "TURKU", "NAANT", "RAISI", "SALO", "FORSS", "PORI",
    "RAUMA", "UUSIK", "VAASA", "SEINA", "KOKKO", "PIETA", "OULU", "RAAHE",
    "TORNIO", "KEMI", "ROVAN", "SODAN", "KITTIL", "KOLARI", "MUONI", "IVALO",
    "INARI", "UTSJO", "KUUSA", "KUOPI", "JOENS", "KAJAAN", "MIKKE", "SAVON",
    "JYVAS", "KEURU", "KOLI", "RUUNA", "PUNKH", "RUKA", "KUUSA2", "MOKKI",
    "SAUNA", "METSA", "RANTA", "JARVI", "LAMPI", "KOSKI", "NIEMI", "SAARI",
    "SILTA", "TORI", "ASEMA", "SATAM", "PELTO", "PURO", "SUO", "VAARA",
    "TUNTU", "LAKSI", "HARJU", "NIITT", "KALLI", "POLKU", "LEIRI", "KOTA",
    "NUOTI", "MAJA", "KYLMA", "LUMI", "MYRSK", "SADE", "RAE", "HELLE",
    "PAKKAS", "TUULI", "AAMU", "ILTA", "YOASE", "KESKI", "STOCK", "UPPSA",
    "GOTEB", "MALMO", "KIRUN", "LULEA", "UMEAA", "OREBR", "VAXJO", "VISBY",
    "OSLO", "BERGN", "TROND", "TROMS", "BODO", "ALTA", "NARVI", "COPEN",
    "AARHU", "ODENS", "AALBO", "REYKJ", "AKURE", "KEFLA", "TALLI", "TARTU",
    "PARNU", "RIGA", "LIEPA", "VILNA", "KAUNA", "KLAIP", "LONDO", "PARIS",
    "BERLI", "MUNICH", "HAMB", "FRANK", "AMSTE", "BRUSS", "ZURIC", "GENEV",
    "VIENN", "PRAGU", "WARSA", "KRAKO", "GDANS", "MADRI", "BARCE", "LISBO",
    "PORTO", "ROME", "MILAN", "VENIC", "NAPLE", "ATHEN", "SOFIA", "BUCHA",
    "BUDAP", "ZAGRE", "LJUBL", "SPLIT", "DUBRO", "SARAJ", "BELGR", "SKOPJ",
    "TIRAN", "DUBLI", "EDINB", "GLASG", "CARDI", "MANC", "LIVER", "BRIST",
    "BATH", "OXFOR", "CAMBR", "YORK", "LEEDS", "NEWCA", "NYC", "BOSTO",
    "CHICA", "MIAMI", "DALLA", "HOUST", "DENVE", "SEATT", "PORTL", "SFO",
    "LAXLOC", "VEGAS", "PHOEN", "TORON", "MONTR", "VANCO", "CALGA", "MEXIC",
    "CANCU", "HAVAN", "BOGOT", "LIMA", "SANTI", "BUENO", "RIO", "SAOPA",
    "CAPE", "NAIRO", "CAIRO", "DUBAI", "DOHA", "MUSCA", "DELHI", "MUMBA",
    "BANGK", "SINGA", "KUALA", "JAKAR", "MANIL", "HANOI", "TOKYO", "OSAKA",
    "SEOUL", "TAIPE", "HONGK", "SHANG", "BEIJI", "SYDNE", "MELBO", "PERTH",
    "AUCKL",
]

WXMOR_LOCATIONS: list[str] = list(
    dict.fromkeys(
        WXMOR_ICAO_LOCATIONS
        + WXMOR_IATA_LOCATIONS
        + WXMOR_LOCAL_LOCATIONS
    )
)